### ISSUE TITLE
Using undefined values to generate pointcloud

### ISSUE THREAD

**Issue by stridera** [ZendarInc/zendar_ros_driver#18]
Here, you're using things like `point.az` and `point.el` before you assign them.
https://github.com/ZendarInc/zendar_ros_driver/blob/3d8af5695b2b249d8c326438b2f8edfe2d20bb75/src/zendar_driver_node.cc#L164

**Comment by MarcBrau** [comment]
@stridera: Thank you for pointing out this issue. It should be fixed when #19 is merged.
